### ISSUE TITLE
IRI validation is incorrect

### ISSUE THREAD

**Issue by fugu13** [yetanalytics/xapi-schema#17]
I don't know all the bits it misses, but as an example, extension keys can be any IRI, yet this is rejected:

```"extensions":{"foo:/a": 1}```

Per the IRI EBNF, in https://www.ietf.org/rfc/rfc3987.txt , an IRI always has a scheme, followed by a colon, followed by an ihier-part; one legal ihier-part is an ipath-absolute, which is

```"/" [ isegment-nz *( "/" isegment ) ]```

, making "/a" an ipath-absolute.

I played around a bit further, and the validation also seems to reject pluses in schemes and have restrictions on scheme length, when a scheme's EBNF is this:

```ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )```

**Comment by milt** [comment]
Thanks for submitting these! We had a bit of fun on a branch a while back using [Instaparse](https://github.com/Engelberg/instaparse) to validate directly against the grammars. Not efficient, but fun. https://github.com/yetanalytics/xapi-schema/tree/fun_with_abnf
