### ISSUE TITLE
Timestamp RegEx

### ISSUE THREAD

**Issue by bsboiko** [yetanalytics/xapi-schema#43]
Currently our RegEx matches ISO 8601 timestamps that look like this: 

2017-09-05T18:36:37Z

But, the following timestamp without any delimiting characters is also valid:

20170905T183637Z

It seems that the cljs-time library returns ISO 8601 timestamps without the characters and that is failing our RegEx.

**Comment by milt** [comment]
@bsboiko is this still an issue? We could remove the separator requirement if it is OK with [this too](https://www.ietf.org/rfc/rfc3339.txt)

**Comment by kelvinqian00** [comment]
Can a source be cited for allowing non-colon-separated times? [RFC 3339](https://tools.ietf.org/html/rfc3339#ref-ISO8601) specify that hours, minutes, and seconds must be colon-separated in the ABNF:
```
   date-fullyear   = 4DIGIT
   date-month      = 2DIGIT  ; 01-12
   date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on
                             ; month/year
   time-hour       = 2DIGIT  ; 00-23
   time-minute     = 2DIGIT  ; 00-59
   time-second     = 2DIGIT  ; 00-58, 00-59, 00-60 based on leap second
                             ; rules
   time-secfrac    = "." 1*DIGIT
   time-numoffset  = ("+" / "-") time-hour ":" time-minute
   time-offset     = "Z" / time-numoffset

   partial-time    = time-hour ":" time-minute ":" time-second
                     [time-secfrac]
   full-date       = date-fullyear "-" date-month "-" date-mday
   full-time       = partial-time time-offset

   date-time       = full-date "T" full-time
```

**Comment by kelvinqian00** [comment]
Closing this issue as non-colon-separated timestamps are not allowed.
