### ISSUE TITLE
Duration allows some invalid durations

### ISSUE THREAD

**Issue by fugu13** [yetanalytics/xapi-schema#5]
Some invalid durations allowed. First, a couple bad for obvious reasons:
```
P
PT
```
Second, it allows multiple fractional durations, but in ISO 8601 only the last time element in the provided duration can be fractional. An example:
```
P10.3DT1.7S
```

**Comment by milt** [comment]
Formed that regex from RFC 3339, doesn't have the fractional stuff. Keeping this open.
