### ISSUE TITLE
Mailto allow standalone percent signs

### ISSUE THREAD

**Issue by fugu13** [yetanalytics/xapi-schema#6]
Percent signs must be part of hex escape sequences or themselves escaped in mailto URIs/IRIs, as they're an escape/delimiter character, per https://tools.ietf.org/html/rfc6068. Example invalid mailto allowed by the validator:
```
mailto:user%@example.com
```

**Comment by canweriotnow** [comment]
Yeh, I just saw this on the spec list... we'll tackle these ASAP, but PR's are welcome!
