### ISSUE TITLE
Valid ISO 8601 Date/Time with Leap Second is rejected

### ISSUE THREAD

**Issue by fugu13** [yetanalytics/xapi-schema#7]
Leap seconds have the number 60; this is valid but rejected by the validator (it's the actual leap second that'll happen later this year):

```
2015-06-30T23:59:60Z
```

**Comment by canweriotnow** [comment]
I believe the validator expects to coerce to `java.util.Date` or js `Date` obj, could be an issue there... @milt might have a better idea. Thanks!

**Comment by milt** [comment]
@canweriotnow no coercion here. Just [the usual](https://www.youtube.com/watch?v=-5wpm-gesOY)
