### ISSUE TITLE
UUID Regex outdated

### ISSUE THREAD

**Issue by FeLungs** [yetanalytics/xapi-schema#70]
Currently, `xapi-schema.spec.regex/UuidRegEx` matches against v4 UUIDs only.

The xAPI spec no longer mandates that v4 is used.

https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#44-uuids

> It is recommended variant 2 in RFC 4122 is used.

**Comment by kelvinqian00** [comment]
Fixed in PR #71
