### ISSUE TITLE
Version does not handle tagged versions properly

### ISSUE THREAD

**Issue by fugu13** [yetanalytics/xapi-schema#8]
Semantic Versioning allows for suffix tags, such as 1.0.0-rc1

The xAPI spec, per https://github.com/adlnet/xAPI-Spec/blob/master/xAPI.md#lrs-requirements-1 , requires the LRS to accept versions starting with "1.0." if they are otherwise valid. The validator rejects 1.0.0-rc1 , which it should accept.

While checking that I noticed the validator also accepts "1.0." as a version, which is not a legal semantic version.

**Comment by canweriotnow** [comment]
Nice catch. I was unaware the spec allowed tagged versions, need to add tagged versions and malformed versions to the test suite.
